version: '3.3'
services:

  frontend:
    image: zakongyka/frontend:v1
    volumes:
      - ../frontend/:/app/result_build/

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgresql_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: zakongyka/backend:V1
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    command: >
        sh -c 'python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               python manage.py runserver 0.0.0.0:8000'
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - backend

volumes:
  postgresql_volume:
  static_volume:
  media_volume: