# Generated by Django 3.2.13 on 2022-11-18 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_formula', '0003_auto_20221115_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(help_text='Добавьте рецепт к этому тегу', on_delete=django.db.models.deletion.CASCADE, to='food_formula.recipe', verbose_name='Рецепт')),
                ('tag', models.ForeignKey(help_text='Добавьте теги рецепта', on_delete=django.db.models.deletion.CASCADE, to='food_formula.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Теги рецепта',
                'verbose_name_plural': 'Теги рецепта',
            },
        ),
        migrations.AddConstraint(
            model_name='tagrecipe',
            constraint=models.UniqueConstraint(fields=('tag', 'recipe'), name='unique_tagrecipe'),
        ),
    ]
